background = #111316
foreground = #A3ABB8
cursor-color = #3b82f6
selection-background = #2F343C
selection-foreground = #E5E7EB
palette = 0=#3f4451
palette = 1=#e05561
palette = 2=#6CDD5F
palette = 3=#F1FA8C
palette = 4=#4aa5f0
palette = 5=#FF79C6
palette = 6=#8BE9FD
palette = 7=#F8F8F2
palette = 8=#4f5666
palette = 9=#ff616e
palette = 10=#7CED71
palette = 11=#FFFFA5
palette = 12=#4dc4ff
palette = 13=#FF92DF
palette = 14=#A4FFFF
palette = 15=#FFFFFF
