background #111316
foreground #A3ABB8
cursor #3b82f6
selection_background #2F343C
selection_foreground #E5E7EB
color0 #3f4451
color1 #e05561
color2 #6CDD5F
color3 #F1FA8C
color4 #4aa5f0
color5 #FF79C6
color6 #8BE9FD
color7 #F8F8F2
color8 #4f5666
color9 #ff616e
color10 #7CED71
color11 #FFFFA5
color12 #4dc4ff
color13 #FF92DF
color14 #A4FFFF
color15 #FFFFFF
